# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'managed': False, 'ordering': ['-date_created']},
        ),
    ]
