# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0003_auto_20170223_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='evaluation_id',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='final_approval_id',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='review_id',
            field=models.NullBooleanField(),
        ),
    ]
