# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0004_auto_20170223_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='evaluation_id',
            new_name='evaluation',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='final_approval_id',
            new_name='final_approval',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='review_id',
            new_name='review',
        ),
    ]
