# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0005_auto_20170223_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='evaluation',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='final_approval',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='review',
            field=models.NullBooleanField(default=False),
        ),
    ]
