# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0005_auto_20170127_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False, 'ordering': ['-date_created']},
        ),
    ]
