# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 16:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0006_auto_20170223_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='approval_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_street_address', models.CharField(max_length=200)),
                ('recipient_city', models.CharField(max_length=100)),
                ('recipient_state', models.CharField(choices=[('AK', 'AK'), ('AL', 'AL'), ('AR', 'AR'), ('AZ', 'AZ'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DC', 'DC'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('IA', 'IA'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('MA', 'MA'), ('MD', 'MD'), ('ME', 'ME'), ('MI', 'MI'), ('MN', 'MN'), ('MO', 'MO'), ('MS', 'MS'), ('MT', 'MT'), ('NC', 'NC'), ('ND', 'ND'), ('NE', 'NE'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NV', 'NV'), ('NY', 'NY'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VA', 'VA'), ('VT', 'VT'), ('WA', 'WA'), ('WI', 'WI'), ('WV', 'WV'), ('WY', 'WY')], max_length=2)),
                ('recipient_zip', models.CharField(blank=True, help_text='Zip code', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Valid zip code format: XXXXX or XXXXX-XXXX', regex='(^[0-9]{5}(?:-[0-9]{4})?$|^$)')])),
                ('recipient_org', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_email', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(max_length=200)),
                ('letter_content', models.TextField()),
                ('cc_1', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_1_org', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_1_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cc_2', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_2_org', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_2_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cc_3', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_3_org', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_3_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cc_4', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_4_org', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_4_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cc_5', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_5_org', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_5_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cc_6', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_6_org', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_6_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepwise.Process')),
            ],
            options={
                'db_table': 'stepwise_approval_letter',
            },
        ),
    ]
