# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 00:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0008_auto_20170130_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='opp_lead_ph',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the form 'XXX-XXX-XXXX'. Area code is required.", regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='tech_contact_ph',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the form 'XXX-XXX-XXXX'. Area code is required.", regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
    ]
