# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 18:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stepwise', '0009_auto_20170130_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='opp_lead_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='opp_lead_org',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='opp_lead_ph',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the form 'XXX-XXX-XXXX'. Area code is required.", regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='tech_contact_org',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
