# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 20:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0010_auto_20170131_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='landowner_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='landowner_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the form 'XXX-XXX-XXXX'. Area code is required.", regex='^[0-9]{3}-[0-9]{3}-[0-9]{4}$')]),
        ),
    ]
