# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0011_auto_20170131_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='anticipated_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='grmw_design_funds',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='landowners_contacted',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='landowners_supportive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='multi_phase',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='opp_lead_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='ph1_standalone',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='tech_contact_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
