# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0012_auto_20170202_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectus',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospectus',
            name='current_step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
