# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0013_auto_20170202_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
