# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0014_auto_20170202_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='prospectus',
            name='landowners_id',
        ),
        migrations.AddField(
            model_name='landowner',
            name='prospectus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.Prospectus'),
        ),
    ]
