# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0016_landowner_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSR', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'stepwise_BSR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BSR_Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSR_Tier', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'stepwise_BSR_Tier',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='BSR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.BSR'),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='BSR_Tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.BSR_Tier'),
        ),
    ]
