# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0017_auto_20170203_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectus',
            name='proposed_atlas_opp_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prospectus',
            name='proposed_atlas_opp_score_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
