# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0018_auto_20170203_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectus',
            old_name='permits_cosultations',
            new_name='permits_consultations',
        ),
    ]
