# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0019_auto_20170203_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectus',
            name='permits_consultations',
        ),
        migrations.AddField(
            model_name='prospectus',
            name='permits_consultations',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='stepwise.Permits_consults'),
            preserve_default=False,
        ),
    ]
