# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0020_auto_20170203_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectus',
            name='permits_consultations',
        ),
        migrations.AddField(
            model_name='prospectus',
            name='permits_consultations',
            field=models.ManyToManyField(blank=True, to='stepwise.Permits_consults'),
        ),
    ]
