# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0021_auto_20170203_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectus',
            name='permits_consultations',
        ),
        migrations.DeleteModel(
            name='Permits_consults',
        ),
    ]
