# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0022_auto_20170203_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permits_consults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_consult_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stepwise_permit_consult',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='prospectus',
            name='permits_consultations',
            field=models.ManyToManyField(blank=True, to='stepwise.Permits_consults'),
        ),
    ]
