# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 17:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0023_auto_20170203_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='anticipated_year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Anticipated Implementation Year must be numerical in the format XXXX, example: 2016.', regex='^[0-9]{4}$')]),
        ),
    ]
