# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0024_auto_20170206_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='grmw_design_funds',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
