# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0026_auto_20170206_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='funds_request_option',
            field=models.CharField(blank=True, choices=[('Option 1', 'BPA works directly with Sponsor/Opportunity Lead (OL) to create a Statement of Work (SOW) for engineering services for a specific project.  Technical assistance from Civil Engineer can be requested by OL to develop SOW.  BPA would contract directly with the consultant via BPA’s pre-qualified consultants list (QVL) and manage the contract.  The contract would include provisions that include the required coordination and integration with the OL during the life of the contract.'), ('Option 2', 'With assistance from BPA, OL develops a SOW for engineering services for a specific project then advertises for consultant services.  Once a selection is made BPA would contract directly with consultant and manage the contract.  The contract would include provisions that include the required coordination and integration with the OL during the life of the contract. This is consistent with the current process for BPA’s implementation contracting and similar to the process that USBR uses in their tributary habitat contracting with improvements (i.e. OL collaboration in SOW development).')], max_length=50, null=True),
        ),
    ]
