# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0027_auto_20170206_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='funds_request_option',
            field=models.CharField(blank=True, choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workspecialties',
            name='work_specialty',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type_desc',
            field=models.CharField(max_length=200),
        ),
    ]
