# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0028_auto_20170206_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='current_step',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
