# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0029_process_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='tech_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
