# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0030_auto_20170208_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectus',
            name='landowners_contribution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
