# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0031_prospectus_landowners_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bsr',
            old_name='BSR',
            new_name='bsr',
        ),
        migrations.RenameField(
            model_name='bsr_tier',
            old_name='BSR_Tier',
            new_name='bsr_tier',
        ),
        migrations.RemoveField(
            model_name='prospectus',
            name='BSR',
        ),
        migrations.RemoveField(
            model_name='prospectus',
            name='BSR_Tier',
        ),
        migrations.AddField(
            model_name='prospectus',
            name='bsr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr'),
        ),
        migrations.AddField(
            model_name='prospectus',
            name='bsr_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr_tier'),
        ),
    ]
