# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0035_auto_20170209_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='bsr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr'),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='bsr_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr_tier'),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='restoration_activities',
            field=models.ManyToManyField(blank=True, related_name='activities', to='stepwise.Activities'),
        ),
    ]
