# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stepwise.models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0036_auto_20170209_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=stepwise.models.get_prospectus_upload_path),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='bsr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr'),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='bsr_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr_tier'),
        ),
    ]
