# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepwise', '0038_auto_20170213_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectus',
            name='bsr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr'),
        ),
        migrations.AlterField(
            model_name='prospectus',
            name='bsr_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stepwise.bsr_tier'),
        ),
    ]
