# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('atlas_desc', models.TextField(blank=True, null=True)),
                ('p_score_cal_factor', models.FloatField(default=0.0)),
                ('u_score_cal_factor', models.FloatField(default=0.0)),
                ('final_p_score', models.FloatField(default=0.0)),
                ('final_u_score', models.FloatField(default=0.0)),
                ('chinook_mult', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'atlas_atlas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='current_cond_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('poor', models.FloatField(default=0.0)),
                ('good', models.FloatField(default=0.0)),
                ('fair', models.FloatField(default=0.0)),
                ('excellent', models.FloatField(default=0.0)),
                ('tbd', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'atlas_current_cond_scoring',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='current_temp_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('poor', models.FloatField(default=0.0)),
                ('good', models.FloatField(default=0.0)),
                ('fair', models.FloatField(default=0.0)),
                ('excellent', models.FloatField(default=0.0)),
                ('tbd', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'atlas_current_temp_scoring',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='future_cond_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('poor', models.FloatField(default=0.0)),
                ('good', models.FloatField(default=0.0)),
                ('fair', models.FloatField(default=0.0)),
                ('excellent', models.FloatField(default=0.0)),
                ('tbd', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'atlas_future_cond_scoring',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='geomorphic_potential_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('low', models.FloatField(default=0.0)),
                ('med', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('tbd', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'atlas_geomorphic_potential_scoring',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atlas',
            name='current_cond_scoring_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.current_cond_scoring'),
        ),
        migrations.AddField(
            model_name='atlas',
            name='current_temp_scoring_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.current_temp_scoring'),
        ),
        migrations.AddField(
            model_name='atlas',
            name='future_cond_scoring_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.future_cond_scoring'),
        ),
        migrations.AddField(
            model_name='atlas',
            name='geomorphic_potential_scoring_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.geomorphic_potential_scoring'),
        ),
    ]
