# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas',
            name='current_cond_scoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.current_cond_scoring'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='current_temp_scoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.current_temp_scoring'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='future_cond_scoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.future_cond_scoring'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='geomorphic_potential_scoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.geomorphic_potential_scoring'),
        ),
    ]
