# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 16:54
from __future__ import unicode_literals

import atlas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_auto_20170306_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='atlas_change_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_log_file', models.FileField(blank=True, null=True, upload_to=atlas.models.upload_change_log_path)),
                ('atlas_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas')),
            ],
        ),
    ]
