# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_auto_20170307_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='life_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_stage_name', models.CharField(max_length=500)),
                ('apr_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apr_a', to='atlas.p_period')),
                ('apr_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apr_b', to='atlas.p_period')),
                ('aug_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aug_a', to='atlas.p_period')),
                ('aug_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aug_b', to='atlas.p_period')),
                ('dec_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dec_a', to='atlas.p_period')),
                ('dec_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dec_b', to='atlas.p_period')),
                ('feb_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feb_a', to='atlas.p_period')),
                ('feb_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feb_b', to='atlas.p_period')),
                ('jan_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jan_a', to='atlas.p_period')),
                ('jan_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jan_b', to='atlas.p_period')),
                ('jul_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jul_a', to='atlas.p_period')),
                ('jul_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jul_b', to='atlas.p_period')),
                ('jun_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jun_a', to='atlas.p_period')),
                ('jun_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jun_b', to='atlas.p_period')),
                ('mar_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mar_a', to='atlas.p_period')),
                ('mar_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mar_b', to='atlas.p_period')),
                ('may_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='may_a', to='atlas.p_period')),
                ('may_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='may_b', to='atlas.p_period')),
                ('nov_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nov_a', to='atlas.p_period')),
                ('nov_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nov_b', to='atlas.p_period')),
                ('oct_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oct_a', to='atlas.p_period')),
                ('oct_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oct_b', to='atlas.p_period')),
                ('sep_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sep_a', to='atlas.p_period')),
                ('sep_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sep_b', to='atlas.p_period')),
            ],
            options={
                'db_table': 'atlas_life_stage',
            },
        ),
        migrations.CreateModel(
            name='p_species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=500)),
                ('life_stage', models.ManyToManyField(blank=True, to='atlas.life_stage')),
            ],
            options={
                'db_table': 'atlas_p_species',
            },
        ),
        migrations.CreateModel(
            name='periodicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsr', models.CharField(max_length=500)),
                ('p_species', models.ManyToManyField(to='atlas.p_species')),
            ],
            options={
                'db_table': 'atlas_periodicity',
            },
        ),
    ]
