# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_life_stage_p_species_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='life_stage',
            name='bsr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='life_stage',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
