# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_auto_20170307_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life_stage',
            name='apr_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apr_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='apr_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apr_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='aug_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aug_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='aug_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aug_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='dec_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dec_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='dec_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dec_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='feb_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feb_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='feb_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feb_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='jan_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jan_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='jan_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jan_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='jul_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jul_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='jul_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jul_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='jun_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jun_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='jun_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jun_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='mar_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mar_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='mar_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mar_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='may_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='may_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='may_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='may_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='nov_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nov_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='nov_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nov_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='oct_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oct_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='oct_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oct_b', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='sep_a',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sep_a', to='atlas.p_period'),
        ),
        migrations.AlterField(
            model_name='life_stage',
            name='sep_b',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sep_b', to='atlas.p_period'),
        ),
    ]
