# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0007_auto_20170307_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='bsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('geomorphic_potential', models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], max_length=50, null=True)),
                ('current_habitat_cond', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('TBD', 'TBD')], max_length=50, null=True)),
                ('current_temp', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('TBD', 'TBD')], max_length=50, null=True)),
                ('future_cond', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('TBD', 'TBD')], max_length=50, null=True)),
                ('u_score', models.IntegerField(blank=True, null=True)),
                ('p_score', models.IntegerField(blank=True, null=True)),
                ('geomorphic_score', models.IntegerField(blank=True, null=True)),
                ('current_cond_score', models.IntegerField(blank=True, null=True)),
                ('future_score', models.IntegerField(blank=True, null=True)),
                ('cumulative_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atlas_bsr',
            },
        ),
        migrations.CreateModel(
            name='bsr_tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'atlas_bsr_tier',
            },
        ),
        migrations.RemoveField(
            model_name='atlas',
            name='final_p_score',
        ),
        migrations.RemoveField(
            model_name='atlas',
            name='final_u_score',
        ),
        migrations.AddField(
            model_name='bsr',
            name='atlas_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas'),
        ),
        migrations.AddField(
            model_name='bsr',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodicity', to='atlas.periodicity'),
        ),
        migrations.AddField(
            model_name='bsr',
            name='tier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.bsr_tier'),
        ),
    ]
