# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0008_auto_20170307_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bsr',
            new_name='atlas_bsr',
        ),
        migrations.RenameModel(
            old_name='bsr_tier',
            new_name='atlas_bsr_tier',
        ),
    ]
