# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:33
from __future__ import unicode_literals

import atlas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlas', '0009_auto_20170307_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='bsr_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=atlas.models.upload_bsr_comment)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bsr_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas_bsr')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'atlas_bsr_comment',
            },
        ),
        migrations.CreateModel(
            name='restoration_actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('direct', models.NullBooleanField()),
                ('indirect', models.NullBooleanField()),
            ],
            options={
                'db_table': 'atlas_restoration_actions',
            },
        ),
    ]
