# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:49
from __future__ import unicode_literals

import atlas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0010_bsr_comment_restoration_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas_bsr',
            name='final_geomorphic_cond_score',
            field=models.IntegerField(blank=True, null=True, verbose_name=atlas.models.atlas_bsr._calc_geomorphic),
        ),
    ]
