# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0011_atlas_bsr_final_geomorphic_cond_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='final_geomorphic_cond_score',
        ),
    ]
