# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0013_remove_atlas_bsr_geomorphic_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='current_cond_score',
        ),
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='future_score',
        ),
    ]
