# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0014_auto_20170308_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='cumulative_score',
        ),
    ]
