# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0015_remove_atlas_bsr_cumulative_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas_bsr',
            name='p_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='atlas_bsr',
            name='u_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
