# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0016_auto_20170308_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas_bsr',
            name='p_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atlas_bsr',
            name='u_score',
            field=models.IntegerField(default=0),
        ),
    ]
