# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0017_auto_20170308_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas_bsr',
            name='u_score',
            field=models.FloatField(default=0.0),
        ),
    ]
