# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0018_auto_20170308_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atlas_bsr',
            old_name='p_score',
            new_name='raw_p_score',
        ),
        migrations.RenameField(
            model_name='atlas_bsr',
            old_name='u_score',
            new_name='raw_u_score',
        ),
    ]
