# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0019_auto_20170309_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='atlas_bsr',
            name='periodicity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodicity_id', to='atlas.periodicity'),
        ),
    ]
