# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0020_auto_20170309_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='life_stage_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.FloatField(default=0.0)),
                ('med', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('none_apply', models.FloatField(default=0.0)),
                ('atlas_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_stage_atlas_id', to='atlas.p_species')),
                ('species_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_stage_species_id', to='atlas.p_species')),
            ],
            options={
                'db_table': 'atlas_life_stage_scoring',
            },
        ),
        migrations.RemoveField(
            model_name='life_stage',
            name='bsr',
        ),
        migrations.RemoveField(
            model_name='life_stage',
            name='species',
        ),
    ]
