# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0021_auto_20170309_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life_stage_scoring',
            name='atlas_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_stage_atlas_id', to='atlas.atlas'),
        ),
    ]
