# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0022_auto_20170309_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'atlas_species',
            },
        ),
        migrations.RemoveField(
            model_name='life_stage_scoring',
            name='species_id',
        ),
        migrations.RemoveField(
            model_name='p_species',
            name='species_name',
        ),
        migrations.AddField(
            model_name='life_stage',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.species'),
        ),
        migrations.AddField(
            model_name='life_stage_scoring',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.species'),
        ),
    ]
