# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0023_auto_20170309_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_species',
            name='species_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.species'),
        ),
    ]
