# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0024_p_species_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life_stage',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atlas.species'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='life_stage_scoring',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atlas.species'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='p_species',
            name='species_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atlas.species'),
            preserve_default=False,
        ),
    ]
