# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0025_auto_20170309_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='hard_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='soft_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
