# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0026_auto_20170309_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='periodicity_id',
        ),
        migrations.RemoveField(
            model_name='periodicity',
            name='bsr',
        ),
        migrations.AddField(
            model_name='periodicity',
            name='bsr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas_bsr'),
        ),
    ]
