# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0028_auto_20170309_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_species',
            name='life_stage',
        ),
        migrations.RemoveField(
            model_name='p_species',
            name='species_name',
        ),
        migrations.RemoveField(
            model_name='periodicity',
            name='p_species',
        ),
        migrations.DeleteModel(
            name='p_species',
        ),
    ]
