# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0030_life_stage_bsr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='life_stage',
            old_name='bsr',
            new_name='bsr_id',
        ),
    ]
