# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 23:27
from __future__ import unicode_literals

import atlas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlas', '0031_auto_20170309_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='periodicity_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=atlas.models.upload_periodicity_comment)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('periodicity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.periodicity')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'atlas_periodicity_comment',
            },
        ),
        migrations.CreateModel(
            name='utilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilization_name', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('bsr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas_bsr')),
            ],
            options={
                'db_table': 'atlas_utilization',
            },
        ),
        migrations.CreateModel(
            name='utilization_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.species')),
                ('utilization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.utilization')),
            ],
            options={
                'db_table': 'atlas_utilization_score',
            },
        ),
        migrations.RenameModel(
            old_name='life_stage_scoring',
            new_name='fish_use_scoring',
        ),
        migrations.AlterModelTable(
            name='fish_use_scoring',
            table='atlas_fish_use_scoring',
        ),
    ]
