# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0032_auto_20170309_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='raw_u_score',
        ),
    ]
