# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0033_remove_atlas_bsr_raw_u_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas',
            name='chinook_mult',
        ),
    ]
