# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0034_remove_atlas_chinook_mult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life_stage',
            name='bsr_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas_bsr'),
            preserve_default=False,
        ),
    ]
