# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0035_auto_20170313_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas_bsr',
            name='raw_p_score',
        ),
    ]
