# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0036_remove_atlas_bsr_raw_p_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='limiting_factor_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('high_direct', models.FloatField(default=0.0)),
                ('high_indirect', models.FloatField(default=0.0)),
                ('med_direct', models.FloatField(default=0.0)),
                ('med_indirect', models.FloatField(default=0.0)),
                ('low_direct', models.FloatField(default=0.0)),
                ('low_indirect', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'atlas_limiting_factor_scoring',
            },
        ),
        migrations.AddField(
            model_name='atlas',
            name='limiting_factor_scoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.limiting_factor_scoring'),
        ),
    ]
