# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0037_auto_20170313_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='limiting_factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'atlas_limiting_factor',
            },
        ),
    ]
