# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0038_limiting_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiting_factor',
            name='ecological_concern',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
