# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0039_limiting_factor_ecological_concern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limiting_factor',
            old_name='name',
            new_name='sub_concern',
        ),
        migrations.AddField(
            model_name='limiting_factor',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
