# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0040_auto_20170313_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='limiting_factor_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('bsr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas_bsr')),
            ],
            options={
                'db_table': 'atlas_limiting_factor_instance',
            },
        ),
        migrations.CreateModel(
            name='limiting_factor_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('limiting_factor_instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.limiting_factor_instance')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.species')),
            ],
            options={
                'db_table': 'atlas_limiting_factor_score',
            },
        ),
        migrations.AlterModelOptions(
            name='limiting_factor',
            options={'ordering': ['ecological_concern']},
        ),
        migrations.RenameField(
            model_name='atlas',
            old_name='limiting_factor_scoring',
            new_name='limiting_factor_scoring_id',
        ),
        migrations.AddField(
            model_name='limiting_factor_instance',
            name='limiting_factor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.limiting_factor'),
        ),
    ]
