# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0041_auto_20170313_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.CharField(choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], max_length=50)),
                ('atlas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas')),
                ('limiting_factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.limiting_factor')),
            ],
            options={
                'ordering': ['limiting_factor_id'],
                'db_table': 'atlas_crosswalk',
            },
        ),
        migrations.RemoveField(
            model_name='restoration_actions',
            name='direct',
        ),
        migrations.RemoveField(
            model_name='restoration_actions',
            name='indirect',
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='rest_action_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.restoration_actions'),
        ),
    ]
