# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0042_auto_20170313_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='restoration_action_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('low', models.FloatField(blank=True, null=True)),
                ('low_immediate', models.FloatField(blank=True, null=True)),
                ('low_long_term', models.FloatField(blank=True, null=True)),
                ('med', models.FloatField(blank=True, null=True)),
                ('med_immediate', models.FloatField(blank=True, null=True)),
                ('med_long_term', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('high_immediate', models.FloatField(blank=True, null=True)),
                ('high_long_term', models.FloatField(blank=True, null=True)),
                ('tbd', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atlas_restoration_action_scoring',
            },
        ),
        migrations.AlterModelOptions(
            name='crosswalk',
            options={'ordering': ['-rest_action_id', '-limiting_factor_id']},
        ),
        migrations.AddField(
            model_name='atlas',
            name='restoration_action_scoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.restoration_action_scoring'),
        ),
    ]
