# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0043_auto_20170317_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='restoration_actions_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immediate', models.CharField(blank=True, choices=[('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('long_term', models.CharField(blank=True, choices=[('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('bsr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas_bsr')),
                ('restoration_action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.restoration_actions')),
            ],
            options={
                'db_table': 'atlas_restoration_actions_score',
            },
        ),
    ]
