# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0044_restoration_actions_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoration_actions_score',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], max_length=50, null=True),
        ),
    ]
