# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0045_auto_20170317_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoration_actions_score',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
