# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0046_restoration_actions_score_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restoration_actions_score',
            old_name='comments',
            new_name='comment',
        ),
    ]
