# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0047_auto_20170317_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atlas',
            old_name='restoration_action_scoring',
            new_name='restoration_action_scoring_id',
        ),
    ]
