# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0048_auto_20170317_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='natural_process_scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlas_name', models.CharField(max_length=100)),
                ('habitat_creation', models.FloatField(blank=True, null=True)),
                ('partial_restoration', models.FloatField(blank=True, null=True)),
                ('full_restoration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atlas_natural_process_scoring',
            },
        ),
        migrations.AddField(
            model_name='atlas',
            name='natural_process_scoring_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.natural_process_scoring'),
        ),
    ]
