# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0049_auto_20170321_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='bsr_opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=200)),
                ('natural_process', models.CharField(choices=[('Habitat Creation', 'Habitat Creation'), ('Partial Restoration', 'Partial Restoration'), ('Full Restoration', 'Full Restoration')], default='Habitat Creation', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('bsr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.atlas_bsr')),
            ],
            options={
                'db_table': 'atlas_bsr_opportunity',
            },
        ),
        migrations.CreateModel(
            name='bsr_opportunity_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.restoration_actions_score')),
                ('opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.bsr_opportunity')),
            ],
            options={
                'db_table': 'atlas_bsr_opportunity_action',
            },
        ),
    ]
