# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0050_bsr_opportunity_bsr_opportunity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsr_opportunity',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
