# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0051_bsr_opportunity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsr_opportunity',
            name='zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
