# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0052_bsr_opportunity_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='opportunity_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'atlas_opportunity_status',
            },
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atlas.opportunity_status'),
        ),
    ]
