# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0053_auto_20170328_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity_status',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Planning & Construction', 'Planning & Construction'), ('Completed', 'Completed')], max_length=30),
        ),
    ]
