# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0054_auto_20170328_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsr_opportunity',
            name='water_flow_rate',
            field=models.CharField(choices=[('N/A', 'N/A'), ('< 0.5', '< 0.5'), ('0.5 - 2.5', '0.5 - 2.5'), ('> 2.5', '> 2.5')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='water_right_date',
            field=models.CharField(choices=[('N/A', 'N/A'), ('1867-1869', '1867-1869'), ('1870-1879', '1870-1879'), ('1880-1889', '1880-1889'), ('1890-1899', '1890-1899'), ('1900-1909', '1900-1909')], default='N/A', max_length=20),
        ),
    ]
