# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0055_auto_20170328_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsr_opportunity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
