# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0056_bsr_opportunity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsr_opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
