# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0057_auto_20170404_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_constuction_effort',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_design_effort',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_landowner_willingness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_regulatory_requirements',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_risk_goal_objectives',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_risk_public_safety',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_site_access_effort',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_sm_dewatering_erosion_ctrl_effort',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='fc_value',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('TBD', 'TBD')], default='TBD', max_length=20),
        ),
    ]
