# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0059_auto_20170406_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limiting_factor',
            name='sub_id',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='limiting_factor_score',
            name='rating',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], default='N/A', max_length=50, null=True),
        ),
    ]
