# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0061_auto_20170410_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsr_opportunity',
            name='center',
            field=models.TextField(blank=True, null=True),
        ),
    ]
