# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0062_bsr_opportunity_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoration_actions_score',
            name='comment',
            field=models.TextField(blank=True, default='No Comment', null=True),
        ),
    ]
