# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0063_auto_20170414_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_temp_scoring',
            name='lethal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='current_temp_scoring',
            name='ok',
            field=models.FloatField(default=0.0),
        ),
    ]
