# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0064_auto_20170417_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas',
            name='p_score_mode',
            field=models.BooleanField(choices=[('Single Species', True), ('Multi Species', False)], default=False),
        ),
        migrations.AlterField(
            model_name='atlas_bsr',
            name='current_temp',
            field=models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('TBD', 'TBD'), ('Lethal', 'Lethal'), ('Ok', 'Ok')], max_length=50, null=True),
        ),
    ]
