# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0065_auto_20170418_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas',
            name='p_score_mode',
            field=models.BooleanField(choices=[(True, 'Single Species'), (False, 'Multi Species')], default=False),
        ),
        migrations.AlterField(
            model_name='restoration_actions_score',
            name='immediate',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restoration_actions_score',
            name='long_term',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High'), ('N/A', 'N/A')], default='N/A', max_length=50, null=True),
        ),
    ]
