# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0066_auto_20170418_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsr_opportunity',
            name='immediate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='limiting_factor_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='long_term_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='longitudinal_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='natural_process_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='restoration_action_priority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='total_bbs_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='water_flow_rate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bsr_opportunity',
            name='water_right_date_score',
            field=models.FloatField(default=0.0),
        ),
    ]
