# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0068_periodicity_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicity',
            old_name='comment',
            new_name='notes',
        ),
    ]
