# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0069_auto_20170628_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas',
            name='opp_map_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
