# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0070_atlas_opp_map_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas',
            name='opp_map_center',
            field=models.TextField(blank=True, null=True),
        ),
    ]
