# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-30 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0071_atlas_opp_map_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas_bsr',
            name='periodicity_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity_status',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Planning & Construction', 'Planning & Construction'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], max_length=30),
        ),
    ]
