# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0072_auto_20170630_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas_bsr',
            name='saved_cumulative_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atlas_bsr',
            name='saved_p_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atlas_bsr',
            name='saved_u_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
