# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboardmeeting',
            name='location_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boardmeeting', to='board.EventsMeetinglocation'),
        ),
    ]
