# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20161215_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboardmeeting',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.EventsMeetinglocation'),
        ),
    ]
