# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20161215_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmeetinglocation',
            name='url',
        ),
        migrations.AddField(
            model_name='eventsmeetinglocation',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=45.3246, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsmeetinglocation',
            name='lon',
            field=models.DecimalField(decimal_places=20, default=118.0877, max_digits=25),
            preserve_default=False,
        ),
    ]
