# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20161215_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmeetinglocation',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='eventsmeetinglocation',
            name='lon',
        ),
        migrations.AddField(
            model_name='eventsmeetinglocation',
            name='address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
