# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20161215_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboardmeeting',
            name='agenda_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_id', to='board.EventsDocument'),
        ),
        migrations.AlterField(
            model_name='eventsboardmeeting',
            name='minutes_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes_id', to='board.EventsDocument'),
        ),
    ]
