# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20161219_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboardmeeting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventsdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventsdocumenttype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventsmeetinglocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
