# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_eventsdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsdocument',
            name='file',
            field=models.FileField(null=True, upload_to='static/documents/board/uploaded/minutes&agenda/'),
        ),
    ]
