# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20161220_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboardmeeting',
            name='agenda_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_id', to='board.EventsDocument'),
        ),
        migrations.AlterField(
            model_name='eventsboardmeeting',
            name='minutes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes_id', to='board.EventsDocument'),
        ),
    ]
