from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(species)
admin.site.register(future_cond_scoring)
admin.site.register(geomorphic_potential_scoring)
admin.site.register(current_cond_scoring)
admin.site.register(current_temp_scoring)
admin.site.register(atlas)
admin.site.register(atlas_change_log)
admin.site.register(p_period)
admin.site.register(life_stage)
admin.site.register(periodicity)
admin.site.register(atlas_bsr)
admin.site.register(atlas_bsr_tier)
admin.site.register(fish_use_scoring)
admin.site.register(utilization)
admin.site.register(utilization_score)
admin.site.register(limiting_factor)
admin.site.register(limiting_factor_scoring)
admin.site.register(limiting_factor_instance)
admin.site.register(limiting_factor_score)
admin.site.register(crosswalk)
admin.site.register(restoration_actions)
admin.site.register(restoration_actions_score)
admin.site.register(restoration_action_scoring)
admin.site.register(natural_process_scoring)
admin.site.register(bsr_opportunity)
admin.site.register(bsr_opportunity_action)
admin.site.register(opportunity_status)