# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ripples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('url', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=7)),
                ('pub_date', models.DateField()),
            ],
            options={
                'db_table': 'publications_ripples',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ripplesarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=300)),
                ('ripples_id', models.ForeignKey(db_column='ripples_id', on_delete=django.db.models.deletion.CASCADE, to='home.Ripples')),
            ],
            options={
                'db_table': 'publications_ripplesarticle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ripplesedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editionname', models.CharField(db_column='editionName', max_length=10)),
            ],
            options={
                'db_table': 'publications_ripplesedition',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ripples',
            name='edition_id',
            field=models.ForeignKey(db_column='edition_id', on_delete=django.db.models.deletion.CASCADE, to='home.Ripplesedition'),
        ),
    ]
