# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdbproject',
            options={'managed': True},
        ),
    ]
