# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161003_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdbproject',
            options={'managed': False},
        ),
    ]
