# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161220_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contactrole',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datetype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gps',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='organizationrole',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='projectboundary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='projectlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ripples',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ripplesarticle',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ripplesedition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='speciesrel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tasksubtype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'managed': False},
        ),
    ]
