# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161003_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsRipples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('url', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=7)),
                ('pub_date', models.DateField()),
                ('edition_id', models.IntegerField()),
            ],
            options={
                'db_table': 'publications_ripples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationsRipplesarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=300)),
                ('ripples_id', models.IntegerField()),
            ],
            options={
                'db_table': 'publications_ripplesarticle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationsRipplesedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editionname', models.CharField(db_column='editionName', max_length=10)),
            ],
            options={
                'db_table': 'publications_ripplesedition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RipplesRipples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=7)),
                ('pub_date', models.DateField()),
                ('thumb', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ripples_ripples',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RipplesRipplesarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'ripples_ripplesarticle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RipplesRipplesedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editionname', models.CharField(db_column='editionName', max_length=10)),
            ],
            options={
                'db_table': 'ripples_ripplesedition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RipplesRipplesyears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ripples_ripplesyears',
                'managed': False,
            },
        ),
    ]
