# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161220_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
