# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20161220_1700'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='projectdb_contact',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='projectdb_contract',
        ),
        migrations.AlterModelTable(
            name='date',
            table='projectdb_date',
        ),
        migrations.AlterModelTable(
            name='datetype',
            table='projectdb_datetype',
        ),
        migrations.AlterModelTable(
            name='document',
            table='projectdb_document',
        ),
        migrations.AlterModelTable(
            name='documenttype',
            table='projectdb_documenttype',
        ),
        migrations.AlterModelTable(
            name='gps',
            table='projectdb_gps',
        ),
        migrations.AlterModelTable(
            name='list',
            table='projectdb_list',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='projectdb_organization',
        ),
        migrations.AlterModelTable(
            name='organizationrole',
            table='projectdb_organizationrole',
        ),
        migrations.AlterModelTable(
            name='organizationtype',
            table='projectdb_organizationtype',
        ),
        migrations.AlterModelTable(
            name='projectboundary',
            table='projectdb_projectboundary',
        ),
        migrations.AlterModelTable(
            name='projectlist',
            table='projectdb_projectlist',
        ),
        migrations.AlterModelTable(
            name='site',
            table='projectdb_site',
        ),
        migrations.AlterModelTable(
            name='species',
            table='projectdb_species',
        ),
        migrations.AlterModelTable(
            name='speciesrel',
            table='projectdb_speciesrel',
        ),
        migrations.AlterModelTable(
            name='statustype',
            table='projectdb_statustype',
        ),
        migrations.AlterModelTable(
            name='task',
            table='projectdb_task',
        ),
        migrations.AlterModelTable(
            name='tasksubtype',
            table='projectdb_tasksubtype',
        ),
        migrations.AlterModelTable(
            name='tasktype',
            table='projectdb_tasktype',
        ),
    ]
