# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161220_1703'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactrole',
            table='projectdb_contactrole',
        ),
        migrations.AlterModelTable(
            name='contacttype',
            table='projectdb_contacttype',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projectdb_project',
        ),
    ]
