# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20161222_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fundingorg_id',
            field=models.ForeignKey(blank=True, db_column='fundingOrg_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Organizationtype'),
        ),
    ]
