# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20161223_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
