# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20161229_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
    ]
