# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20161229_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Statustype'),
        ),
    ]
