# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20170104_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
    ]
