# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170105_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(max_length=200, upload_to=home.models.get_image_path)),
                ('date', models.DateField()),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
            options={
                'db_table': 'projectdb_image',
                'managed': True,
            },
        ),
    ]
