# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dropboxURL', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
            options={
                'db_table': 'projectdb_video',
                'managed': True,
            },
        ),
    ]
