# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extension',
            field=models.CharField(default='wmv', max_length=10),
            preserve_default=False,
        ),
    ]
