# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170110_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='extension',
        ),
    ]
