# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_video_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ortho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbFile', models.FileField(max_length=200, upload_to=home.models.get_ortho_path)),
                ('downloadURL', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
            options={
                'db_table': 'projectdb_ortho',
                'managed': True,
            },
        ),
    ]
