# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_ortho'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
