# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_video_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'ordering': ('name', 'fiscalyear')},
        ),
    ]
