# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20170127_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipplesSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'publications_subscribers',
            },
        ),
    ]
