# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_ripplessubscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripplessubscribers',
            name='confirmation_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ripplessubscribers',
            name='confirmed',
            field=models.NullBooleanField(),
        ),
    ]
