# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20170531_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripplessubscribers',
            name='confirmed',
            field=models.NullBooleanField(default=False),
        ),
    ]
