# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20170531_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripplessubscribers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 1, 10, 35, 51, 174179)),
            preserve_default=False,
        ),
    ]
