# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_ripplessubscribers_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripples',
            name='file',
            field=models.FileField(null=True, upload_to=home.models.get_ripple_path),
        ),
    ]
