# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_ripples_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripples',
            name='url',
        ),
    ]
