# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_ripples_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripples',
            name='thumb_file',
            field=models.FileField(null=True, upload_to=home.models.get_ripple_thumb_path),
        ),
    ]
